config/routes.rb
Rails.application.routes.draw do

  get 'webnotifications/index'
  get 'category/delete'
  devise_scope :user do
    get 'after_signup_page', to: 'devise/registrations#after_signup'
  end
  devise_for :users , controllers: {registrations: "users/registrations", confirmations: "users/confirmations"}
  get 'userproduct/create'
  get 'userproduct/delete'
  get 'userproduct/findID'
  get 'product/show'
  get 'product/observed'
  get 'product/all'
  #get 'product/index'
  get 'home/about'
  get 'productshop/create'
  get 'productshop/getData'
  resources :productshop
  resources :userproduct
  resources :product
  resources :shop
  resources :category
  resources :webnotifications
  get 'public/adminfun'
  get 'product/observed'
  #nowy
  get 'search', to: "product#search"
  get 'search_by_category', to: "product#search_by_category"
  get 'search_by_category', to: "userproduct#search_by_category"
  #get 'public/home'
  root 'public#home'
  get "/public", to: "public#home"
  get 'settings/unsubscribe'
  get 'settings/update'
  #devise_for :users
  resources :contacts, only: [:new, :create]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/404' , to: 'errors#not_found'
  get '/422' , to: 'errors#unacceptable'
  get '/500' , to: 'errors#server_error'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Big Boundle Company', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Produkty', product_all_url, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'O nas', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Kontakt', new_contact_path, class:"nav-link" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">

        <% if user_signed_in? %>
          <% if current_user.admin==true %>
            <li><%= link_to 'Funkcje Admina', public_adminfun_path, class:"nav-link" %></li>
            <% end %>
          <li><%= link_to 'Produkty Obserwowane', product_observed_path, class:"nav-link" %></li>
          <li><%= link_to 'Edytuj profil', edit_user_registration_path, class:"nav-link" %></li>
          <li><%= link_to 'Wyloguj się',  destroy_user_session_path, method: :delete, class:"nav-link" %></li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Zaloguj się', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Zarejestruj się', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>O nas</h1>
Tutaj znajdują sie informacje o nas