config/routes.rb
Rails.application.routes.draw do

  get 'webnotifications/index'
  get 'category/delete'
  devise_scope :user do
    get 'after_signup_page', to: 'devise/registrations#after_signup'
  end
  devise_for :users , controllers: {registrations: "users/registrations", confirmations: "users/confirmations"}
  get 'userproduct/create'
  get 'userproduct/delete'
  get 'userproduct/findID'
  get 'product/show'
  get 'product/observed'
  get 'product/all'
  #get 'product/index'
  get 'home/about'
  get 'productshop/create'
  get 'productshop/getData'
  resources :productshop
  resources :userproduct
  resources :product
  resources :shop
  resources :category
  resources :webnotifications
  get 'public/adminfun'
  get 'product/observed'
  #nowy
  get 'search', to: "product#search"
  get 'search_by_category', to: "product#search_by_category"
  get 'search_by_category', to: "userproduct#search_by_category"
  #get 'public/home'
  root 'public#home'
  get "/public", to: "public#home"
  get 'settings/unsubscribe'
  get 'settings/update'
  #devise_for :users
  resources :contacts, only: [:new, :create]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/404' , to: 'errors#not_found'
  get '/422' , to: 'errors#unacceptable'
  get '/500' , to: 'errors#server_error'
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :product_category, :dependent => :destroy
  has_one :category, :through=> :product_category
  has_many :user_product, :dependent => :destroy
  has_many :users, :through=> :user_product
  has_many :product_shop, :dependent => :destroy
  has_many :shops, :through=> :product_shop

  paginates_per 6
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  helper_method :sort_column, :sort_direction


    def observed
       @products = current_user.products.order(sort_column + " " + sort_direction).order(:product_id).page(params[:page])
    end
    def all
      @products = Product.order(sort_column + " " + sort_direction).page(params[:page])
    end

    def search
      @products = Product.where("lower(name) LIKE ? OR name LIKE ?", "%" + params[:q] + "%", "%" + params[:q] + "%").page(params[:page])
    end
  def search_by_category

    to_show=ProductCategory.where(category_id: params[:category_id])
    zmienna=[]
    to_show.each do |prod|
      zmienna << prod.product_id
    end
    @products=Product.where(id: zmienna).page(params[:page])
  end


  def show
      @products = Product.find(params[:id])
      @product_shops=@products.product_shop.order(date: :desc, price: :asc).first
    end
  # ponizej deklaruje sie domyslne sortowanie
  # teraz jest ustawione tak zeby sortowalo po dacie dodania produktu od najnowszego
    private
    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/all.html.erb
<head>

  <h1>Listing Products</h1>
</head>
<body>
<% name= current_user.present? ? current_user.login : "(Nie zalogowany)" %>
<div> Uzytkownik: <%= name %></div>




</thead>
</table>
</br>

<%= sortable "name", "Sortuj po nazwie" %>
<%= form_tag("/search_by_category", method: 'get') do%>
  <%=label_tag(:category_id, "Filtruj po kategorii") %>
  <%= select_tag("category_id", options_from_collection_for_select(Category.all, "id", "name")) %>
  <%= submit_tag "Filtruj", class: "btn btn-success" %>
  <br>
<%end %>

<%= render 'layouts/grid' %>


</body>
<br>

app/views/product/filtr.html.erb
<h1>Search Results</h1>
<div class="album text-muted">
  <div class="container">
    <div class="row">
        <% @products.each do |product| %>
          <div class="card">
            <strong class="card-text"><%= product.name %></strong>
            <%if !product.category.nil? %>
              <p class="card-text"><%= product.category.name %></p>
            <%end %>
            <p class="card-text"><%= product.brand %></p>
            <%=link_to image_tag(product.image, style: "width: 250px; height: auto" ), product_path(product.id),class: "nav-link" %>
            <% if current_user %>
              <% if !current_user.products.exists?(product.id) %>
                <%= form_tag(userproduct_create_path, method: "get") do %>

                  <%= hidden_field_tag :product_id, product.id %>
                  <br/>
                  <%= submit_tag "Dodaj do Obserwowanych", style: "position: absolute;
                  bottom: 5px;
                  left: 0;
                  ", class: "btn btn-dark" %>
                <% end %>
              <%else %>
                <%= form_tag(userproduct_delete_path, method: :get)  do %>
                  <%= hidden_field_tag :product_id, product.id%>
                  <br/>
                  <%= submit_tag "Usun z Obserwowanych" , style: "position: absolute;
                  bottom: 5px;
                  left: 0;
                  ", class: "btn btn-dark"%>
                <% end %>

              <% end%>

              </div>

            <% end %>

        <% end %>
    </div>
    <%= paginate @products %>
    <div class="row">
      <div class="col-md-12">
      </div>

    </div>

  </div>

</div>

app/views/product/observed.html.erb
<head>

  <h1>Produkty Obserwowane</h1>
</head>
<body>
<%=button_to "Chcę otrzymywać notyfikacje", webnotifications_path, :class=>"btn btn-primary", :method => :get%>



</thead>
</table>
</br>
<%= sortable "name", "Sortuj po nazwie" %>
<%= render 'layouts/grid' %>


</body>
<br>

app/views/product/search.erb
<h1>Search Results</h1>
<%= render 'layouts/grid' %>

app/views/product/search_by_category.html.erb
<h1>Search by category Results</h1>
<%= render 'layouts/grid' %>

app/views/product/show.html.erb
<head>

</head>
<strong class="card-text"><%= @products.name %></strong>

<%if !@products.category.nil? %>
  <p class="card-text"><%= @products.category.name %></p>
<%end %>
<p class="card-text"><%= @products.brand %></p>
<img style="width: 250px; height: auto" src='<%=@products.image%>'/>
<br/>
<br/>
<br/>
<br/>
<h3> Najlepsza oferta w tej chwili</h3>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <th scope="col">Nazwa Sklepu</th>
    <th scope="col">Cena</th>
    <th scope="col">Data</th>
  </thead>
  <tbody>
      <tr>
          <td><p class="card-text"><%= @product_shops.shop.name %></p></td>
          <td><p class="card-text"><%= @product_shops.price %></p></td>
          <td><p class="card-text"><%= @product_shops.date %></p></td>
      </tr>
  </tbody>
</table>

<%#= line_chart(@data) %>
<%= line_chart ProductShop.where(product_id: @products.id).group(:shop_id, :date).maximum(:price),
   title:"Zmiany w cenach", xtitle: "Data", ytitle: "Cena",suffix: "zł",download:true, discrete: false%>
<%#= line_chart ProductShop.group(:price).group_by_day(:created_at).count %>

<% @products.shops.group(:id).sort().each do |shop| %>
  <p>ID: <%=shop.id %> odpowiada sklepowi: <%=shop.name %></p>
<% end %>